### ISSUE TITLE
Issue and PR "staleness" 

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/8Knot#100]
**Please describe the background and context for this new visualization**
When looking at PRs and Issues how many:

- Have not been commented on in 7 days 
- have not been closed or merged in a variable amount of time (7 day and 30 days)

**Describe the perspective you'd like the final visual to give**
TBD. Must determine best graph representation

**Acceptance criteria for the issue and visualization to be complete**
- [ ] Augur Query
- [ ] Preprocess data into pandas data frame format for visualization
- [ ] Plotly graph creation
- [ ] Notes with any background context that would be useful for Explorer integration 
- [ ] Open issue on explorer for visualization integration using template

**Additional context**

**Comment by JamesKunstle** [comment]
@cdolfi Is this done?

**Comment by cdolfi** [comment]
@JamesKunstle will be closing with PR coming out later today
