### ISSUE TITLE
" KeyError: 'created' " for some empty data.

### ISSUE THREAD

**Issue by JamesKunstle** [sandiego-rh/8Knot#155]
**Describe the bug**
When the search bar only includes some repos, we have the above error when we try to execute a line like: 
df_created = pd.DataFrame(df_issues["created"])
because the dataset is empty.

**To Reproduce**
1. Search for quay/alas
2. Check logs- no created_at column available.

**Expected behavior**
Should report a blank graph but we're not handling that correctly.

**Screenshots**

**Additional context**

**Comment by cdolfi** [comment]
@JamesKunstle Is this something that is still an issue?

**Comment by JamesKunstle** [comment]
closing- this happens when a worker query returns no data so the dataframe is empty -fixed for the moment but being optimized later.
